

development:
  adapter: postgresql
  encoding: unicode
  database: conradbastable_development
  pool: 5
  username: cbastable
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: conradbastable_test
  pool: 5
  username: cbastable
  password: